export const userActionTypes = {
    FETCH_USERS_START: "FETCH_USERS_START",
    FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
    FETCH_USERS_FAILURE: "FETCH_USERS__FAILURE",
    FETCH_USER_DETAIL: "FETCH_USER_DETAIL",
    CREATE_NEW_USER: "CREATE_NEW_USER",
    CREATE_NEW_USER_FAILURE: "CREATE_NEW_USER_FAILURE",
    EDIT_USER: "EDIT_USER"
}